"""Constants used by the koolnova-bms component."""

DOMAIN = "koolnova_bms"

NUM_ZONES = 16

REG_PER_ZONE = 4
REG_ENABLED = 1
REG_MODE = 2
REG_TARGET_TEMP = 3
REG_CURRENT_TEMP = 4

REG_AIRFLOW = 65
REG_AC_TARGET_TEMP = 69
REG_AC_TARGET_FAN_MODE = 73
REG_SERIAL_CONFIG = 77
REG_SLAVE_ID = 78
REG_EFFICIENCY = 79
REG_SYSTEM_ENABLED = 81
REG_SYS_KN_MODE = 82

FIRST_ZONE_REGISTER = REG_ENABLED
TOTAL_ZONE_REGISTERS = NUM_ZONES * REG_PER_ZONE
FIRST_SYS_REGISTER = REG_AIRFLOW
TOTAL_SYS_REGISTERS = 18

FAN_OFF = 0
FAN_LOW = 1
FAN_MED = 2
FAN_HIGH = 3
FAN_AUTO = 4

MODE_AIR_COOLING = 0x01
MODE_AIR_HEATING = 0x02
MODE_UNDERFLOOR_HEATING = 0x04
MODE_UNDERFLOOR_AIR_COOLING = 0x05
MODE_UNDERFLOOR_AIR_HEATING = 0x06

HOLD_MODE_UNDERFLOOR_ONLY = "underfloor"
HOLD_MODE_FAN_ONLY = "fan"
HOLD_MODE_UNDERFLOOR_AND_FAN = "underfloor and fan"

HVAC_MODE_OFF = "off"
HVAC_MODE_COOL = "cool"
HVAC_MODE_HEAT = "heat"

ACMACHINES = 4

AC1 = 1
AC2 = 2
AC3 = 3
AC4 = 4

HA_COMPONENT_SENSOR = "sensor"
HA_COMPONENT_CLIMATE = "climate"
